export const countryNamesByCode: { [code: string]: string } = {
  ZA: 'South Africa',
  AT: 'Austria',
  IN: 'India',
  AF: 'Afghanistan',
  AL: 'Albania',
  DE: 'Germany',
  AD: 'Andorra',
  AO: 'Angola',
  AI: 'Anguilla',
  AQ: 'Antarctica',
  AG: 'Antigua and Barbuda',
  AN: 'Netherlands Antilles',
  SA: 'Saudi Arabia',
  DZ: 'Algeria',
  AR: 'Argentina',
  AM: 'Armenia',
  AW: 'Aruba',
  AU: 'Australia',
  AZ: 'Azerbaijan',
  BE: 'Belgium',
  BA: 'Bosnia and Herzegovina',
  BS: 'Bahamas',
  BD: 'Bangladesh',
  BH: 'Bahrain',
  BB: 'Barbados',
  BZ: 'Belize',
  BJ: 'Benin',
  BM: 'Bermuda',
  BY: 'Belarus',
  MM: 'Burma',
  BO: 'Bolivia',
  BW: 'Botswana',
  BR: 'Brazil',
  BN: 'Brunei',
  BG: 'Bulgaria',
  BI: 'Burundi',
  BF: 'Burkina Faso',
  BT: 'Bhutan',
  CV: 'Cape Verde',
  CM: 'Cameroon',
  KH: 'Cambodia',
  CA: 'Canada',
  QA: 'Qatar',
  KZ: 'Kazakhstan',
  TD: 'Chad',
  CL: 'Chile',
  CN: 'China',
  CY: 'Cyprus',
  CO: 'Colombia',
  KM: 'Comoros',
  CG: 'Congo-Brazzaville',
  CD: 'Congo-Kinshasa',
  KP: 'North Korea',
  KR: 'South Korea',
  CR: 'Costa Rica',
  CI: 'Ivory Coast',
  HR: 'Croatia',
  CU: 'Cuba',
  DK: 'Denmark',
  DM: 'Dominica',
  EG: 'Egypt',
  AE: 'United Arab Emirates',
  EC: 'Ecuador',
  ER: 'Eritrea',
  SK: 'Slovakia',
  SI: 'Slovenia',
  ES: 'Spain',
  EE: 'Estonia',
  US: 'United States',
  ET: 'Ethiopia',
  FO: 'Faroe Islands',
  FJ: 'Fiji',
  PH: 'Philippines',
  FI: 'Finland',
  FR: 'France',
  GM: 'Gambia',
  GA: 'Gabon',
  GH: 'Ghana',
  GE: 'Georgia',
  GS: 'South Georgia and the South Sandwich Islands',
  GI: 'Gibraltar',
  GR: 'Greece',
  GD: 'Grenada',
  GL: 'Greenland',
  GP: 'Guadeloupe',
  GU: 'Guam',
  GT: 'Guatemala',
  GY: 'Guyana',
  GF: 'French Guiana',
  GN: 'Guinea',
  GQ: 'Equatorial Guinea',
  GW: 'Guinea-Bissau',
  HT: 'Haiti',
  HN: 'Honduras',
  HK: 'Hong Kong',
  HU: 'Hungary',
  YE: 'Yemen',
  BV: 'Bouvet Island',
  NF: 'Norfolk Island',
  CX: 'Christmas Island',
  KY: 'Cayman Islands',
  CK: 'Cook Islands',
  FK: 'Falkland Islands',
  HM: 'Heard Island and McDonald Islands',
  MH: 'Marshall Islands',
  UM: 'United States Minor Outlying Islands',
  SB: 'Solomon Islands',
  TC: 'Turks and Caicos Islands',
  VI: 'U.S. Virgin Islands',
  VG: 'British Virgin Islands',
  CC: 'Cocos Islands',
  ID: 'Indonesia',
  IR: 'Iran',
  IQ: 'Iraq',
  IE: 'Ireland',
  IS: 'Iceland',
  IL: 'Israel',
  IT: 'Italy',
  JM: 'Jamaica',
  JP: 'Japan',
  DJ: 'Djibouti',
  JO: 'Jordan',
  YU: 'Yugoslavia',
  KW: 'Kuwait',
  LB: 'Lebanon',
  LY: 'Libya',
  LA: 'Laos',
  LS: 'Lesotho',
  LV: 'Latvia',
  LR: 'Liberia',
  LI: 'Liechtenstein',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  MX: 'Mexico',
  MC: 'Monaco',
  MO: 'Macau',
  MK: 'Macedonia',
  MG: 'Madagascar',
  MY: 'Malaysia',
  MW: 'Malawi',
  MV: 'Maldives',
  ML: 'Mali',
  MT: 'Malta',
  MP: 'ds',
  MA: 'Morocco',
  MQ: 'Martinique',
  MU: 'Mauritius',
  MR: 'Mauritania',
  YT: 'Mayotte',
  FM: 'Micronesia',
  MZ: 'Mozambique',
  MD: 'Moldova',
  MN: 'Mongolia',
  MS: 'Montserrat',
  NE: 'Niger',
  NA: 'Namibia',
  NR: 'Nauru',
  NP: 'Nepal',
  NI: 'Nicaragua',
  NG: 'Nigeria',
  NU: 'Niue',
  NO: 'Norway',
  NC: 'New Caledonia',
  NZ: 'New Zealand',
  OM: 'Oman',
  NL: 'Netherlands',
  PW: 'Palau',
  PA: 'Panama',
  PG: 'Papua New Guinea',
  PK: 'Pakistan',
  PY: 'Paraguay',
  PE: 'Peru',
  PN: 'Pitcairn',
  PL: 'Poland',
  PF: 'French Polynesia',
  PR: 'Puerto Rico',
  PT: 'Portugal',
  KE: 'Kenya',
  KG: 'Kyrgyzstan',
  KI: 'Kiribati',
  RU: 'Russia',
  GB: 'United Kingdom',
  CF: 'Central African Republic',
  CZ: 'Czech Republic',
  DO: 'Dominican Republic',
  RE: 'Reunion',
  RO: 'Romania',
  RW: 'Rwanda',
  KN: 'Saint Kitts and Nevis',
  SM: 'San Marino',
  PM: 'Saint Pierre and Miquelon',
  ST: 'Sao Tome and Principe',
  VC: 'Saint Vincent and the Grenadines',
  SY: 'Syria',
  SV: 'El Salvador',
  WS: 'Samoa',
  AS: 'American Samoa',
  SH: 'Saint Helena',
  LC: 'Saint Lucia',
  EH: 'Western Sahara',
  SC: 'Seychelles',
  SN: 'Senegal',
  SL: 'Sierra Leone',
  SG: 'Singapore',
  SO: 'Somalia',
  LK: 'Sri Lanka',
  SE: 'Sweden',
  CH: 'Switzerland',
  SZ: 'Swaziland',
  SD: 'Sudan',
  SR: 'Suriname',
  SJ: 'Svalbard and Jan Mayen',
  TH: 'Thailand',
  TW: 'Taiwan',
  TJ: 'Tajikistan',
  TZ: 'Tanzania',
  IO: 'British Indian Ocean Territory',
  TF: 'French Southern Territories',
  TL: 'Timor-Leste',
  TG: 'Togo',
  TK: 'Tokelau',
  TO: 'Tonga',
  TT: 'Trinidad and Tobago',
  TN: 'Tunisia',
  TM: 'Turkmenistan',
  TR: 'Turkey',
  TV: 'Tuvalu',
  UA: 'Ukraine',
  UG: 'Uganda',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VU: 'Vanuatu',
  VA: 'Vatican City',
  VE: 'Venezuela',
  VN: 'Vietnam',
  WF: 'Wallis and Futuna',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
}
